name: test

on:
    push:
        branches:
            - main
            - 'releases/*'
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest, macos-14]
                node-version: [16, 18, 20]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: |
                  npm install -g pnpm
                  pnpm install
            - name: Run tests (Linux)
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                  npm run test
              shell: bash
            - name: Run tests (macOS)
              if: ${{ matrix.os == 'macos-latest' || matrix.os == 'macos-14' }}
              run: |
                  npm run test
              shell: zsh {0}
            - name: Run tests (Windows)
              if: ${{ matrix.os == 'windows-latest' }}
              run: |
                  npm run test
              shell: powershell
